#version 430 core

layout (local_size_x = 1000, local_size_y = 1, local_size_z = 1) in;

// ----------------------------------------------------------------------------
//
// Uniforms
//
// ----------------------------------------------------------------------------

layout (location = 0) uniform float Dt;                 /**< Time since the previous simulation step */
layout (location = 1) uniform vec2 FramebufferSize;     /**< Framebuffer size */
layout (location = 2) uniform vec2 Attractor;           /**< Attractor position */
layout (location = 3) uniform float AttractorForce;     /**< Scale applied to the velocity toward the attractor */

/** Buffer containing particle positions */
layout (std430, binding = 0) buffer PositionBuffer {
    vec2 positions[];
};

/** Buffer containing particle velocities */
layout (std430, binding = 1) buffer VelocitiesBuffer {
    vec2 velocities[];
};

// ----------------------------------------------------------------------------
//
// Functions
//
// ----------------------------------------------------------------------------

/**
 * Computes a pseudo-random value from a 2D vector
 *
 * @param xi                    2D vector used as the random seed
 *
 * @return Pseudo-random value
 */
float rand(vec2 xi){
    return fract(sin(dot(xi.xy, vec2(12.9898,78.233))) * 43758.5453);
}


/**
 * Entry point for the compute shader
 */
void main() {
    // Read position and velocity from the shader storage buffers
    vec2 position = positions[gl_GlobalInvocationID.x];
    vec2 velocity = velocities[gl_GlobalInvocationID.x];

    // Calculate the velocity toward the attractor.
    vec2 attractorVector = Attractor - position;
    float attractorDistance = length(attractorVector);
    vec2 attractorVelocity = 50000*normalize(attractorVector) / max(0.5, attractorDistance);

    // Calculate a random velocity
    vec2 randomVelocity = 2*vec2(rand(attractorVector + gl_GlobalInvocationID.xy)) - vec2(1);

    // Calculate angular velocity
    vec2 rotationalVelocity = cross(vec3(attractorVector, 0), vec3(0, 0, 1)).xy;
    rotationalVelocity = smoothstep(100, 0, attractorDistance)*rotationalVelocity;

    // Simulate particle inertia
    velocity = mix(velocity, AttractorForce*(attractorVelocity + rotationalVelocity + 5*randomVelocity), 0.05);

    // Handle the framebuffer boundaries
    {
        if (position.x < 0) {
            velocity.x *= -1;
            position.x = 0;
        } else if (position.x > FramebufferSize.x) {
            velocity.x *= -1;
            position.x = FramebufferSize.x;
        }

        if (position.y < 0) {
            velocity.y *= -1;
            position.y = 0;
        } else if (position.y > FramebufferSize.y) {
            velocity.y *= -1;
            position.y = FramebufferSize.y;
        }
    }

    // Calculate the new position
    position = position + Dt*velocity;

    // Write position and velocity to the shader storage buffers
    positions[gl_GlobalInvocationID.x] = position;
    velocities[gl_GlobalInvocationID.x] = velocity;
}



