/*
 * Tessellation evaluation shader (TES)
 *
 * The TES runs once for every vertex generated by the fixed-function
 * tessellator. gl_TessCoord locates that vertex inside the abstract patch.
 * The shader uses those coordinates to interpolate the TCS output attributes,
 * calculate a displaced 3D position, and forward the result to rasterization.
 */

 #version 430 core

 // Use a triangle domain, equal spacing, and counter-clockwise winding.
 // Fractional spacing modes provide smoother transitions between levels.
 // 
 layout(triangles, equal_spacing, ccw)in;


 // TCS output attributes; the array length equals the output patch size.
 in TCS_OUT {
	vec3 positionW;
	vec3 normal;
	vec2 texCoords;
 } tes_in[];

 out TES_OUT {
	vec3 positionW;
	vec3 normal;
	vec2 texCoords;
 } tes_out;
  
 uniform sampler2D depthMap;
 uniform float gDispFactor;

 uniform mat4 projection;
 uniform mat4 view;

 // Interpolation helpers
 vec2 interpolate2D(vec2 v0, vec2 v1, vec2 v2) {
	return vec2(gl_TessCoord.x) * v0 + vec2(gl_TessCoord.y) * v1 + vec2(gl_TessCoord.z) * v2;
 }
 
 vec3 interpolate3D(vec3 v0, vec3 v1, vec3 v2)
{
    return vec3(gl_TessCoord.x) * v0 + vec3(gl_TessCoord.y) * v1 + vec3(gl_TessCoord.z) * v2;
} 

 // gl_TessCoord contains the generated vertex's barycentric coordinates.
 vec4 interpolate4D(vec4 v0, vec4 v1, vec4 v2){
	return	gl_TessCoord.x*v0		// Interpolate the three control-point attributes
		+	gl_TessCoord.y*v1		// using the generated vertex's barycentric
		+	gl_TessCoord.z*v2;		// coordinates inside the triangle patch.
 }
 
 void main() {
	/* Quad domains provide 2D coordinates for bilinear interpolation. */

	/* For isolines, x is the position along a line and y selects the line. */
	// float u = gl_TessCoord.x; // Read the tessellation coordinate (u, v).
	// float v = gl_TessCoord.y;

	// Interpolate the attributes of the output vertex using the barycentric coordinates
	tes_out.texCoords = interpolate2D(tes_in[0].texCoords, tes_in[1].texCoords, tes_in[2].texCoords);
	tes_out.normal = interpolate3D(tes_in[0].normal, tes_in[1].normal, tes_in[2].normal);
	tes_out.normal = normalize(tes_out.normal);
	tes_out.positionW = interpolate3D(tes_in[0].positionW, tes_in[1].positionW, tes_in[2].positionW);

	// Displace the vertex along the normal
	float Displacement = 1-texture(depthMap, tes_out.texCoords.xy).x;
	tes_out.positionW += tes_out.normal * Displacement * gDispFactor;

	gl_Position = projection * view * vec4(tes_out.positionW,1.0); // Project the displaced world-space position.
 }

 /*
	// Alternative interpolation approach
	void main() {
		
		float u = gl_TessCoord.x; // Read the tessellation coordinate (u, v).
		float v = gl_TessCoord.y;

		vec4 tmp1 = mix(gl_in[1].gl_Position, gl_in[0].gl_Position, u); // Interpolate one side of the rectangular patch.
		vec4 tmp2 = mix(gl_in[2].gl_Position, gl_in[3].gl_Position, u); // Interpolate the opposite side.

		vec4 position = mix(tmp1, tmp2, v);
		// modify position (extrude along normal ... )
		gl_Position = projection * view * model * position;	
	}
 */


	
	 

